[pyprland]
plugins = ["scratchpads", "expose"]

[scratchpads.term]
animation = "fromTop"
command = "rio --class rio-dropterm"
class = "rio-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50